################################################################################
# Server Configuration
################################################################################

# System log (Morgan) prod or dev
LOG: prod

# Enable cors (cross-origin resource sharing)
CORS: true

# Webpack mode:
#   - development
#   - production 
MODE: development

# JWT user password encryption key (AUTH)
TOKEN_SECRET: token_secreto

# JWT life time
LIMIT_TOKEN:
  MIN: 14
  MAX: 30

# Zones Opeennebula
# -ID: identificator zone
# -RPC: URL connect to RPC (OPENNEBULA)
# -ZEROMQ: URL connect to socket ZEROMQ
# -VNC: URL connect to socket VNC

OPENNEBULA_ZONES: 
  - ID: 0
    RPC: http://localhost:2633/RPC2
    ZEROMQ: 
    VNC:
  - ID: 1
    RPC: http://127.0.0.1:2633/RPC2
    ZEROMQ: 
    VNC:
      - PEPE: dssa
      - COSA: asd
# Presentation information system (Config information)
SYSTEM_DATA:
  NO_AUTH:
    - MODE
    - LIMIT_TOKEN:
        - MAX
    - OPENNEBULA_ZONES:
        - ID
        - VNC:
          - COSA
        - ZEROMQ
  AUTH:
    - MODE
    - OPENNEBULA_ZONES:
        - ID
        - VNC
        - ZEROMQ